# import initial library 

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

# import data 

In [4]:
dataset = pd.read_csv('/content/50_Startups.csv')

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [12]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(X[3])

[144372.41 118671.85 383199.62 'New York']


# transform  column 

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
print(X[1:5, :])

[[1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


#train test split 

In [18]:
from sklearn.model_selection import train_test_split  

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)
x_train.shape, y_train.shape

((40, 6), (40,))

# train on LinearRegressor

In [22]:
from sklearn.linear_model import LinearRegression

In [24]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

# predicting on test set 

In [28]:
y_predict = lr.predict(x_test)
np.set_printoptions(precision=2)
yp = y_predict.reshape(-1, 1)
yt = y_test.reshape(-1,1)
yp, yt

(array([[103015.2 ],
        [132582.28],
        [132447.74],
        [ 71976.1 ],
        [178537.48],
        [116161.24],
        [ 67851.69],
        [ 98791.73],
        [113969.44],
        [167921.07]]), array([[103282.38],
        [144259.4 ],
        [146121.95],
        [ 77798.83],
        [191050.39],
        [105008.31],
        [ 81229.06],
        [ 97483.56],
        [110352.25],
        [166187.94]]))

In [31]:
c = np.concatenate((yp, yt), 1)
c

array([[103015.2 , 103282.38],
       [132582.28, 144259.4 ],
       [132447.74, 146121.95],
       [ 71976.1 ,  77798.83],
       [178537.48, 191050.39],
       [116161.24, 105008.31],
       [ 67851.69,  81229.06],
       [ 98791.73,  97483.56],
       [113969.44, 110352.25],
       [167921.07, 166187.94]])